export const REGISTER_SESSION = "REGISTER_SESSION";
export const DEREGISTER_SESSION = "DEREGISTER_SESSION";
export const SET_PERMISSION = "SET_PERMISSION";
export const REMOVE_PERMISSION = "REMOVE_PERMISSION";
